-- MySQL Script generated by MySQL Workbench
-- 04/05/16 15:40:38
-- Model: Dyon Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dyonweb
-- -----------------------------------------------------
-- Database utilizada no progrma Dyon, para controle de eventos.

-- -----------------------------------------------------
-- Schema dyonweb
--
-- Database utilizada no progrma Dyon, para controle de eventos.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dyonweb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dyonweb` ;

-- -----------------------------------------------------
-- Table `dyonweb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `tipo` INT(11) NOT NULL,
  `sexo` ENUM('m','f') NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `image` VARCHAR(100) NULL DEFAULT NULL,
  `codigo_recuperacao` VARCHAR(32) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`rg` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dyonweb`.`instancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`instancia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `status` INT NOT NULL,
  `id_plano` INT NOT NULL,
  `data_criacao` DATE NOT NULL,
  `id_criador` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_instancia_usuario1_idx` (`id_criador` ASC),
  CONSTRAINT `fk_instancia_usuario1`
    FOREIGN KEY (`id_criador`)
    REFERENCES `dyonweb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dyonweb`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`evento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `max_venda` INT(11) NOT NULL DEFAULT '0',
  `status` INT(11) NOT NULL DEFAULT '2',
  `id_instancia` INT NOT NULL,
  `local` VARCHAR(255) NULL,
  `descricao` TEXT NULL,
  `flag_hospedagem` TINYINT(1) NOT NULL DEFAULT 1,
  `flag_compras` TINYINT(1) NOT NULL DEFAULT 1,
  `flag_grupos` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `id_usuario`),
  INDEX `fk_evento_usuario_idx` (`id_usuario` ASC),
  INDEX `fk_evento_instancia1_idx` (`id_instancia` ASC),
  CONSTRAINT `fk_evento_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dyonweb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_instancia1`
    FOREIGN KEY (`id_instancia`)
    REFERENCES `dyonweb`.`instancia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dyonweb`.`casa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`casa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_evento` INT(11) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `valor_pessoa` FLOAT NOT NULL,
  `numero_vagas` INT(11) NOT NULL DEFAULT '0',
  `anexo_contrato` VARCHAR(32) NULL DEFAULT NULL,
  `mapa` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`, `id_evento`),
  INDEX `fk_casa_evento1_idx` (`id_evento` ASC),
  CONSTRAINT `fk_casa_evento1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `dyonweb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dyonweb`.`categoria_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`categoria_compra` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dyonweb`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`comentario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `node` INT(45) NULL DEFAULT NULL,
  `id_node` INT(45) NULL DEFAULT NULL,
  `texto` MEDIUMTEXT NULL DEFAULT NULL,
  `id_usuario` INT(11) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_comentario_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_comentario_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dyonweb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dyonweb`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`compra` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_evento` INT(11) NOT NULL,
  `id_categoria` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `quantidade` INT(11) NOT NULL,
  `valor_unitario` FLOAT NOT NULL,
  `tipo` INT(11) NOT NULL,
  `status` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `id_evento`),
  INDEX `fk_compra_evento1_idx` (`id_evento` ASC),
  INDEX `fk_compra_categoria_compra1_idx` (`id_categoria` ASC),
  CONSTRAINT `fk_compra_categoria_compra1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `dyonweb`.`categoria_compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_evento1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `dyonweb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dyonweb`.`diretoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`diretoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `acesso_minimo` VARCHAR(45) NULL DEFAULT NULL,
  `id_instancia` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_diretoria_usuario1_idx` (`id_usuario` ASC),
  INDEX `fk_diretoria_instancia1_idx` (`id_instancia` ASC),
  CONSTRAINT `fk_diretoria_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dyonweb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diretoria_instancia1`
    FOREIGN KEY (`id_instancia`)
    REFERENCES `dyonweb`.`instancia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dyonweb`.`diretoria_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`diretoria_usuarios` (
  `id_usuario` INT(11) NOT NULL,
  `id_diretoria` INT(11) NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_diretoria`),
  INDEX `fk_usuario_has_diretoria_diretoria1_idx` (`id_diretoria` ASC),
  INDEX `fk_usuario_has_diretoria_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_usuario_has_diretoria_diretoria1`
    FOREIGN KEY (`id_diretoria`)
    REFERENCES `dyonweb`.`diretoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_diretoria_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dyonweb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dyonweb`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`grupo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_lider` INT(11) NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_evento` INT(11) NOT NULL,
  `codigo_acesso` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`, `id_lider`, `id_evento`),
  UNIQUE INDEX `codigo_acesso_UNIQUE` (`codigo_acesso` ASC),
  INDEX `fk_grupo_usuario1_idx` (`id_lider` ASC),
  INDEX `fk_grupo_evento1_idx` (`id_evento` ASC),
  CONSTRAINT `fk_grupo_evento1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `dyonweb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_usuario1`
    FOREIGN KEY (`id_lider`)
    REFERENCES `dyonweb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dyonweb`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`logs` (
  `id` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tipo_log` INT(11) NOT NULL,
  `mensagem_log` TEXT NOT NULL,
  PRIMARY KEY (`id`, `id_usuario`),
  INDEX `fk_logs_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_logs_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dyonweb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dyonweb`.`lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`lote` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_evento` INT(11) NOT NULL,
  `id_parent` INT NULL,
  `nome` VARCHAR(40) NOT NULL,
  `valor` FLOAT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `max_venda` INT(11) NULL DEFAULT '0',
  `status` INT(11) NOT NULL DEFAULT '0',
  `pagamento_hash` VARCHAR(100) NULL,
  `flag_multisex` TINYINT(1) NOT NULL DEFAULT 0,
  `genero` ENUM('f','m') NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `id_evento`),
  INDEX `fk_lote_evento1_idx` (`id_evento` ASC),
  CONSTRAINT `fk_lote_evento1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `dyonweb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dyonweb`.`metodo_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`metodo_pagamento` (
  `id` INT(11) NOT NULL,
  `id_evento` INT(11) NOT NULL,
  `nome` VARCHAR(70) NOT NULL,
  `max_parcelas` INT(11) NOT NULL,
  `desconto` FLOAT NULL,
  `tipo_comprovante` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_metodo_pagamento_evento1_idx` (`id_evento` ASC),
  CONSTRAINT `fk_metodo_pagamento_evento1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `dyonweb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dyonweb`.`quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`quarto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_casa` INT(11) NOT NULL,
  `numero` INT(11) NOT NULL,
  `numero_vagas` INT(11) NOT NULL,
  `suite` ENUM('s','n') NOT NULL,
  PRIMARY KEY (`id`, `id_casa`),
  INDEX `fk_quarto_casa1_idx` (`id_casa` ASC),
  CONSTRAINT `fk_quarto_casa1`
    FOREIGN KEY (`id_casa`)
    REFERENCES `dyonweb`.`casa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dyonweb`.`pacote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`pacote` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `id_grupo` INT(11) NOT NULL,
  `id_lote` INT(11) NOT NULL,
  `desconto` INT(11) NOT NULL DEFAULT '0',
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tipo_pagamento` INT(11) NOT NULL,
  `status` INT(11) NOT NULL DEFAULT '0',
  `data_alteracao` TIMESTAMP NULL DEFAULT NULL,
  `id_quarto` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `id_usuario`, `id_grupo`, `id_lote`),
  INDEX `fk_pacote_usuario1_idx` (`id_usuario` ASC),
  INDEX `fk_pacote_lote1_idx` (`id_lote` ASC),
  INDEX `fk_pacote_grupo1_idx` (`id_grupo` ASC),
  INDEX `id_quarto` (`id_quarto` ASC),
  CONSTRAINT `fk_idquartoidx`
    FOREIGN KEY (`id_quarto`)
    REFERENCES `dyonweb`.`quarto` (`id`),
  CONSTRAINT `fk_pacotequarto`
    FOREIGN KEY (`id_quarto`)
    REFERENCES `dyonweb`.`quarto` (`id`),
  CONSTRAINT `fk_pacote_grupo1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `dyonweb`.`grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pacote_lote1`
    FOREIGN KEY (`id_lote`)
    REFERENCES `dyonweb`.`lote` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pacote_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dyonweb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dyonweb`.`parcela_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`parcela_compra` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_compra` INT(11) NOT NULL,
  `id_comprovante` VARCHAR(150) NULL DEFAULT NULL,
  `valor` DOUBLE NOT NULL,
  `status` INT(45) NOT NULL,
  `tipo_comprovante` INT(11) NULL DEFAULT NULL,
  `data_vencimento` DATETIME NULL DEFAULT NULL,
  `data_pagamento` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `id_compra`),
  INDEX `fk_parcela_compra_compra1_idx` (`id_compra` ASC),
  CONSTRAINT `fk_parcela_compra_compra1`
    FOREIGN KEY (`id_compra`)
    REFERENCES `dyonweb`.`compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dyonweb`.`parcela_pacote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`parcela_pacote` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_pacote` INT(11) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_vencimento` DATETIME NOT NULL,
  `data_pagamento` DATETIME NULL DEFAULT NULL,
  `valor` FLOAT NOT NULL,
  `status` INT(11) NOT NULL,
  `id_comprovante` VARCHAR(100) NULL DEFAULT NULL,
  `tipo_comprovante` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `id_pacote`),
  INDEX `fk_parcelas_pacote1_idx` (`id_pacote` ASC),
  CONSTRAINT `fk_parcelas_pacote1`
    FOREIGN KEY (`id_pacote`)
    REFERENCES `dyonweb`.`pacote` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dyonweb`.`tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`tarefa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_diretoria` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `titulo` VARCHAR(150) NULL DEFAULT NULL,
  `descricao` LONGTEXT NULL DEFAULT NULL,
  `data_vencimento` DATETIME NULL DEFAULT NULL,
  `data_criacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `prioridade` INT(11) NULL DEFAULT NULL,
  `status` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `fk_tarefa_diretoria1_idx` (`id_diretoria` ASC),
  INDEX `fk_tarefa_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_tarefa_diretoria1`
    FOREIGN KEY (`id_diretoria`)
    REFERENCES `dyonweb`.`diretoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarefa_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dyonweb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `dyonweb`.`instancia_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dyonweb`.`instancia_usuario` (
  `id_instancia` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `status_usuario` INT NOT NULL,
  `evento_padrao` INT NULL,
  `fluxo_padrao` INT NULL,
  `diretoria_padrao` INT NULL,
  `instancia_padrao` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_instancia`, `id_usuario`),
  INDEX `fk_instancia_has_usuario_usuario1_idx` (`id_usuario` ASC),
  INDEX `fk_instancia_has_usuario_instancia1_idx` (`id_instancia` ASC),
  CONSTRAINT `fk_instancia_has_usuario_instancia1`
    FOREIGN KEY (`id_instancia`)
    REFERENCES `dyonweb`.`instancia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instancia_has_usuario_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dyonweb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `dyonweb`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `dyonweb`;
INSERT INTO `dyonweb`.`usuario` (`id`, `nome`, `email`, `senha`, `rg`, `tipo`, `sexo`, `cidade`, `estado`, `data_criacao`, `image`, `codigo_recuperacao`) VALUES (1, 'Admin', 'paul.0@live.de', '5fe841b4ec488fce3cc57a404deec76a', '17763047', 10, 'm', 'Belo Horizonte', 'MG', 'CURRENT_TIMESTAMP', NULL, '0');

COMMIT;


-- -----------------------------------------------------
-- Data for table `dyonweb`.`instancia`
-- -----------------------------------------------------
START TRANSACTION;
USE `dyonweb`;
INSERT INTO `dyonweb`.`instancia` (`id`, `nome`, `status`, `id_plano`, `data_criacao`, `id_criador`) VALUES (1, 'Admin', 1, 1, 'CURRENT_TIMESTAMP', 1);
INSERT INTO `dyonweb`.`instancia` (`id`, `nome`, `status`, `id_plano`, `data_criacao`, `id_criador`) VALUES (2, 'Boemia', 1, 1, 'CURRENT_TIMESTAMP', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `dyonweb`.`instancia_usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `dyonweb`;
INSERT INTO `dyonweb`.`instancia_usuario` (`id_instancia`, `id_usuario`, `status_usuario`, `evento_padrao`, `fluxo_padrao`, `diretoria_padrao`, `instancia_padrao`) VALUES (1, 1, 10, NULL, NULL, NULL, DEFAULT);
INSERT INTO `dyonweb`.`instancia_usuario` (`id_instancia`, `id_usuario`, `status_usuario`, `evento_padrao`, `fluxo_padrao`, `diretoria_padrao`, `instancia_padrao`) VALUES (2, 1, 10, NULL, NULL, NULL, DEFAULT);

COMMIT;

