-- MySQL Script generated by MySQL Workbench
-- 04/04/16 11:26:24
-- Model: Dyon Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdyon
-- -----------------------------------------------------
-- Database utilizada no progrma Dyon, para controle de eventos.

-- -----------------------------------------------------
-- Schema bdyon
--
-- Database utilizada no progrma Dyon, para controle de eventos.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdyon` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bdyon` ;

-- -----------------------------------------------------
-- Table `bdyon`.`lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdyon`.`lote` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_evento` INT(11) NOT NULL,
  `id_parent` INT NULL,
  `nome` VARCHAR(40) NOT NULL,
  `valor` FLOAT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `max_venda` INT(11) NULL DEFAULT '0',
  `status` INT(11) NOT NULL DEFAULT '0',
  `pagamento_hash` VARCHAR(100) NULL,
  `flag_multisex` TINYINT(1) NOT NULL DEFAULT 0,
  `genero` ENUM('f','m') NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `id_evento`),
  INDEX `fk_lote_evento1_idx` (`id_evento` ASC),
  CONSTRAINT `fk_lote_evento1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `bdyon`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
